CREATE DATABASE customer_behavior;
USE customer_behavior;

SELECT * FROM customer limit 5;

-- 1.What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY gender;

-- 2.Top 5 highest spending customers
select customer_id, SUM(purchase_amount) AS total_spent
from customer
group by customer_id
order by total_spent DESC
limit 5;

-- 3. Which customers used a discount but still spent more than the average purchase amount?
SELECT *
FROM customer
WHERE discount_applied = 'Yes'
AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer);

-- 4. Which are the top 5 products with the highest average review rating?
Select item_purchased, round(avg(review_rating),2) as avg_rating
from customer 
group by item_purchased
order by avg_rating desc
limit 5;

-- 5. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type, AVG(purchase_amount) AS avg_purchase
from customer
where shipping_type IN ('Standard', 'Express')
group by shipping_type;

-- 6. Average purchase amount per age group
SELECT age_group, AVG(purchase_amount) AS avg_spend
FROM customer
GROUP BY age_group;

-- 7. Repeat customers
select customer_id, previous_purchases
from customer
where previous_purchases > 20;

-- 8.Do subscribed customers spend more?
--  Compare average spend and total revenue 
--  between subscribers and non-subscribers.
select subscription_status,
		count(customer_id) AS total_customer,
        avg(purchase_amount) AS avg_spend,
        sum(purchase_amount) AS total_revenue
from customer
group by subscription_status
order by total_revenue,avg_spend desc;
-- INSIGHT-> Although subscribers are fewer, their average spending is almost equal, which means they are valuable but not significantly outperforming non-subscribers.


-- 9. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
       ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100 / COUNT(*),2) AS discount_percentage
from customer
group by item_purchased
order by discount_percentage DESC
limit 5;

-- 10.Segment customers into New, Returning, and Loyal based on their 
-- total number of previous purchases, and show the count of each segment.
select COUNT(*) as total_customers,
case 
    when previous_purchases = 1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal'
end as customer_segment
from customer
group by customer_segment;

-- or(second method)

with customer_type as (
select 
case
	when previous_purchases = 1 then "new"
    when previous_purchases between 2 and 10 then "returning"
    else "loyal"
    end as customer_segment
from customer
)
select customer_segment ,count(*) as total_customers
from customer_type
group by customer_segment;

-- 11. What are the top 3 most purchased products within each category?
select * 
from (
	select 
    category, 
    item_purchased,
    sum(purchase_amount) as total_sales,
		rank() over(partition by category order by sum(purchase_amount) desc ) as rnk
from customer 
group by category, item_purchased
)t
where rnk <=3;

-- 12.Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select 
case 
    when previous_purchases > 5 then 'Repeat Buyer'
    else 'Non-Repeat Buyer'
end as customer_type,
subscription_status,
COUNT(*) as total_customers
from customer
group by customer_type, subscription_status;

-- 13. What is the revenue contribution of each age group?
select age_group,
       SUM(purchase_amount) AS total_revenue
from customer
group by age_group
order by total_revenue desc;